name: Action self-test

on:
  release:
    types: [published]

jobs:
  test-action:
    name: Publish release to Notion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # see: https://github.com/nektos/act#module_not_found
      - name: Test the action locally
        uses: ./
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
