name: Action self-test

on:
  release:
    types: [published]

jobs:
  test-action:
    name: Publish release to Notion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matmar10/slack-release
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
